name: workout_app
description: Workout project.

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  #mobx
  mobx: ^2.1.3
  flutter_mobx: ^2.0.6+5
  #modular
  flutter_modular: ^5.0.3
  modular_core: ^2.0.3+1
  
  asuka: ^2.0.0

  #ui
  blurrycontainer: ^1.0.2
  flutter_svg: ^0.23.0
  google_fonts: ^3.0.1

  #animation
  rive: ^0.9.1
  lottie: ^2.1.0

  #system
  email_validator: ^2.1.17

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mobx_codegen: 
  build_runner: 
  modular_codegen: 
  flutter_launcher_icons: ^0.10.0
  
flutter:
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/png/
    - assets/svg/
    - assets/rive/
    - assets/lotties/

